"""remove tabela ativos

Revision ID: 0e20051e0cd4
Revises: af7308c5975a
Create Date: 2026-09-03 21:11:18.091913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e20051e0cd4'
down_revision: Union[str, Sequence[str], None] = 'af7308c5975a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ativos_id'), table_name='ativos')
    op.drop_index(op.f('ix_ativos_ticker'), table_name='ativos')
    op.drop_table('ativos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ativos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ticker', sa.VARCHAR(), nullable=True),
    sa.Column('quantidade', sa.INTEGER(), nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ativos_ticker'), 'ativos', ['ticker'], unique=False)
    op.create_index(op.f('ix_ativos_id'), 'ativos', ['id'], unique=False)
    # ### end Alembic commands ###
