"""adiciona tabela precos_atuais

Revision ID: d54fa88a7d67
Revises: 7ada49fdc496
Create Date: 2026-09-03 21:21:13.352938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd54fa88a7d67'
down_revision: Union[str, Sequence[str], None] = '7ada49fdc496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precos_atuais',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('precos_atuais')
    # ### end Alembic commands ###
